### ISSUE TITLE
Support creating pool members with a hostname

### ISSUE THREAD

**Issue by vsnine** [0xHiteshPatel/appsvcs_integration_iapp#10]
It would be handy if possible to have support to provide an optional hostname for the pool members. I believe this would require the creation or presence of the node already. 

This would be separate from an ephemeral hostname.

**Comment by 0xHiteshPatel** [comment]
Can you give me some more detail here?  A snippet of the tmsh list output of the type of config you would like to create would help a lot.

**Comment by vsnine** [comment]
Of course. Right now if I were to want to use this iApp in an environment where the node entry had been previously added using a hostname or something arbitrary as the name, this iApp will fail stating something like /Common/host1 conflicts with /Common/10.10.10.10%0.  My thought for this would be to allow an optional title for the node to accommodate use of the iApp with existing nodes, or in the case of a non-existing node, create it with the name provided.

Rough example, extra details removed:
If an optional hostname was specified, it would look something like this. Otherwise the node name would be the address with route domain as entered by the user in the iApp template.
ltm node host1 {
  address 10.10.10.10
...
}
ltm pool mypool {
  members {
    host1:http {
      address 10.10.10.10
    }
  }
...
}

**Comment by 0xHiteshPatel** [comment]
Makes sense.  I'll try and get to it this week.

**Comment by 0xHiteshPatel** [comment]
Turns out this was pretty easy.  Just checked in a small fix to allow using the pool member IPAddress field to specify the name of a pre-exsiting node object.  You should be able to enter the node object name in the IPAddress field now and link in the existing node.  Pool members without an associated node already created will be auto-created.  

Give it a try and let me know if this works properly.

**Comment by vsnine** [comment]
Haven't been able to test yet. Version v0.3-022_015 fails validation when attempting to "load sys application template".

root@(mybigip1)(cfg-sync Not All Devices Synced)(/S1-green-P:Standby)(/Common)(tmos)# load sys application template /shared/tmp/appsvcs_integration_v0.3-022_015.tmpl
Loading configuration...
  /shared/tmp/appsvcs_integration_v0.3-022_015.tmpl
Syntax Error:(/shared/tmp/appsvcs_integration_v0.3-022_015.tmpl at line: 1655) "description" unknown property

**Comment by 0xHiteshPatel** [comment]
Just checking in a fix for this... v0.3-023_015.  Can you give it a try?

**Comment by vsnine** [comment]
Thanks! That passes validation. It appears to be functioning pretty well.
