### ISSUE TITLE
Providing cert details with no key causes clientssl profile to not be created with no deployment failure

### ISSUE THREAD

**Issue by vsnine** [0xHiteshPatel/appsvcs_integration_iapp#11]
Deploying the iApp with the SSL certificate field populated but the key field blank results in the iApp deploying without the client-ssl profile created, but it does not throw an error. I feel like filling in one field but not both should cause an exception. It seems like the right thing here is to only go forward if both are filled out or if none are filled out.

Steps to reproduce:
Create a new iApp
Fill in certificate field, leaving key field blank.
Deploy iApp

**Comment by 0xHiteshPatel** [comment]
Looking at the code, the ssl-profile creation is just skipped.  Do you have a log message in /var/tmp/scriptd.out like this:
[proc_client_ssl] ssl cert & key not specified... skipped Client-SSL profile creation

Can you check and see if you see that message?  That way I know that the logic is correct.. just a matter of deciding if a hard error should be thrown or not at that point.

**Comment by 0xHiteshPatel** [comment]
Was able to test this and the logic is correct.  Will be committing a fix to throw a hard error in this case

**Comment by 0xHiteshPatel** [comment]
Checked in fixes to the develop branch.  Closing issue.. please re-open if you see any issues.

**Comment by vsnine** [comment]
New version works well. Thanks!

{ u'code': 400,
  u'errorStack': [],
  u'message': u'script did not successfully complete: (A client-ssl certifcate was specified without a client-ssl key\n    while executing\n"error "A client-ssl certifcate was specified without a client-ssl key""\n    invoked from within\n"if { [string length $vs__ProfileClientSSLKey] > 0 && [string length $vs__ProfileClientSSLCert] > 0 && [string length $vs__ProfileClientSSL] == 0 } {\n ..." line:591)'}
