### ISSUE TITLE
Limit the "Poolconfig Poolmember" Key names to 15 characters 

### ISSUE THREAD

**Issue by pdp2shirts** [0xHiteshPatel/appsvcs_integration_iapp#2]
![image](https://cloud.githubusercontent.com/assets/5025809/8388719/9eb59616-1c1a-11e5-8088-9674298a8f10.png)

On BIg-IQ, these few fields only display 16 characters Max (no word-wrap), and the 16th character is sometimes cut off, so limiting to 15 characters would be preferable

**Comment by 0xHiteshPatel** [comment]
Have updated the template to reduce the size of all field names to account for these types of issues.  While this particular issue is exposed on BIG-IQ, we also are seeing the same type of problem in APIC and NSX mode.

Code is complete and will be checked in after testing is complete.
