### ISSUE TITLE
Can we change the Key Name "Destination Address" and "Destination Mask" to "VIP Address" or "Virtual Server Address"

### ISSUE THREAD

**Issue by pdp2shirts** [0xHiteshPatel/appsvcs_integration_iapp#3]
![image](https://cloud.githubusercontent.com/assets/5025809/8388893/f1cbfe88-1c1c-11e5-94a6-9e72c6fe2068.png)

Can we change the Key Name "Destination Address" and "Destination Mask" to "VIP Address" or "Virtual Server Address." Also change "Service Port" to "VIP Port" or "Virtual Server Port" to distinguish it from the Port of a Pool Member.

**Comment by 0xHiteshPatel** [comment]
Made this and many other updates.  Will be committed in v0.3_003 once testing is complete.  This is what it looks like now:

![image](https://cloud.githubusercontent.com/assets/13039730/8390756/34b7ccf6-1c6b-11e5-8545-eda1864536d8.png)
