### ISSUE TITLE
We are having an issue addingPool Address field

### ISSUE THREAD

**Issue by nopragma** [0xHiteshPatel/appsvcs_integration_iapp#30]
We can't add a full address in the pool address field.

**Comment by 0xHiteshPatel** [comment]
Hi,

Can you give me more details please?  Which version of the template are you using? What are you trying to add in the field?

**Comment by nopragma** [comment]
Hi Hitesh,


We were using the new iapp (attached). If you take a look at the screenshot you can see where we couldn’t add the IP address.


Dan

Dan Smith, CISSP, CEH
Field Systems Engineer
M (714) 906-3149
d.smith@f5.com
f5.com<https://www.f5.com/> | synthesis.f5.com<https://synthesis.f5.com/>
[Twitter]<https://twitter.com/f5networks>[LinkedIn]<http://www.linkedin.com/company/f5-networks>[Facebook]<https://www.facebook.com/f5networksinc>[YouTube]<http://www.youtube.com/f5networksinc>[DevCentral]<https://devcentral.f5.com/>
[F5 Logo and Tagline]
