### ISSUE TITLE
Deploying iApp with Bundled iRule Fails

### ISSUE THREAD

**Issue by zonywhoop** [0xHiteshPatel/appsvcs_integration_iapp#32]
Am attempting to deploy an iApp using a customer build of the appsvcs template v2.0_001.  The only inclusion are 3 iRules that we use on a consistent basis.  2 of these iRules are extremely simple but when you try to use them via the vs__BundledItems table we receive this error:

> Error reported by BigIP: {"code":400,"message":"script did not successfully complete: (can't parse TCL script beginning with\nwhen HTTP_REQUEST {\n    if { [HTTP::uri] contains \"debug=\" } {\n        HTTP::res\n\n    while executing\n\"tmsh::create $bundled_irule_cmd\"\n    (\"foreach\" body line 44)\n    invoked from within\n\"foreach bundled_irule $bundled_irules {\n    debug [list virtual_server bundled_irule create_irule] [format \"deploying bundled iRule %s\" $bundled_irule...\"\n    invoked from within\n\"if { [llength $bundled_irules] > 0 } {\n  set bundled_irule_map [list %APP_PATH%      $app_path \\\n                             %APP_NAME%      $app \\\n ...\" line:2377)","errorStack":[]}
> /Library/Ruby/Gems/2.0.0/gems/rest-client-2.0.0/lib/restclient/abstract_response.rb:223:in `exception_with_response': 400 Bad Request (RestClient::BadRequest)

The iRules code is as follows:
```
when HTTP_REQUEST {
  if {[HTTP::uri] contains "debug=" } {
    HTTP::respond 500 content { We are sorry, but the URL you requested is ILLEGAL.}

    log local0. "Request from [IP::client_addr] for [HTTP::uri] has been rejected." 
  }
}
```

We have a much more complex and longer iRule that works just fine however.  I've been unable to troubleshoot why this does not work.  Any thoughts?

**Comment by 0xHiteshPatel** [comment]
I was able to deploy the iRule you included without issue.  My guess is that there are some control characters in your iRule file that are not being displayed.  I was able to copy and paste the code in this issue into a file using vi and deploy without issue.

You can try seomthing like this:
http://alvinalexander.com/blog/post/linux-unix/how-remove-non-printable-ascii-characters-file-unix

If you still have issues please do the following and send to h.patel <at> f5.com
 - set "iApp: Log Level" to '10'
 - tail -f /var/tmp/scriptd.out on the BIG-IP device
 - save the relevant portion of the log to a text file (strip out any private information)
 - send the following:  log file, the built iApp template file, the iRule as a file attachment

**Comment by zonywhoop** [comment]
OK.. finally got this worked out. 

The issue was that there was no newline after the last } in the .irule files for those that did not work there being one for those that did work.  You can see the difference use the `cat` command as seen below.  The `-ev` switch shows all hidden characters and shows all line endings with `$`.

**Works**
> #! cat -ev testirule_works.irule
> when HTTP_REQUEST {$
>   if {[HTTP::uri] contains "debug=" } {$
>     HTTP::respond 500 content { We are sorry, but the URL you requested is ILLEGAL.}$
> $
>     log local0. "Request from [IP::client_addr] for [HTTP::uri] has been rejected." $
>   }$
> }$

**Fails**
> #! cat -ev testirule_fails.irule
> when HTTP_REQUEST {$
>   if {[HTTP::uri] contains "debug=" } {$
>     HTTP::respond 500 content { We are sorry, but the URL you requested is ILLEGAL.}$
> $
>     log local0. "Request from [IP::client_addr] for [HTTP::uri] has been rejected." $
>   }$
> }

Notice the `$` at the end of the last bracket on the one that works vs missing on the one that fails.

Ed

**Comment by 0xHiteshPatel** [comment]
Ok.  That makes sense.  I'll add some code in the build system to check for a ending newline.
