### ISSUE TITLE
Cannot dynamic endpoint attachment from APIC 2.1

### ISSUE THREAD

**Issue by pavaritSCM** [0xHiteshPatel/appsvcs_integration_iapp#34]
We used appsvcs_integration_v2.0-002_001.tmpl with BIG-IP 11.6.1, iWorkFlow 2.0.2 and APIC 2.1 (1h). We create service graph and enable 'Attachment Notificationand' enter a single pool member with ip address '0.0.0.0'. We plug node to APIC and APIC detect the node but not auto create pool member on BIG-IP (dynamic endpoint)

**Comment by 0xHiteshPatel** [comment]
Hi.  This repository has been retired.  Please reopen your issue here:

https://github.com/F5Networks/f5-application-services-integration-iApp
