### ISSUE TITLE
Edit the Key name "Load Balancing Method" to include parenthetical helper text

### ISSUE THREAD

**Issue by pdp2shirts** [0xHiteshPatel/appsvcs_integration_iapp#4]
![image](https://cloud.githubusercontent.com/assets/5025809/8388940/f0291556-1c1d-11e5-9967-9c2f5f0dcc7e.png)

Could we add a parenthetical comment after "Load Balancing Method" to list the values that can be used here. this Key name looks to be word-wrap enabled, but I'm not certain how many characters long it can be.

something like:

"Load Balancing Method (dynamic-ratio-node, fastest-app-response, fastest-node, least-connections-member, least-connections-node, least-sessions, observed-member, observed-node, predictive-member, predictive-node, round-robin, ratio-member, ratio-node, ratio-session, ratio-least-connections-member, ratio-least-connections-node, weighted-least-connections-member)"

Some of these may not be appropriate to add to the list, but we boast 17 LB methods as a differentiator.

**Comment by 0xHiteshPatel** [comment]
Adding that much text to the description field is problematic to northbound systems.  I believe the correct way to handle this, and other, 'dropdown' fields is to clearly document the available options in a table in the wiki and/or user guide (doesn't exist yet but needs to)

Closing issue for now.  Please re-open if you disagree.
