### ISSUE TITLE
issue with build.sh on a BIG-IP 

### ISSUE THREAD

**Issue by nmenant** [0xHiteshPatel/appsvcs_integration_iapp#7]
i tried to run ./build.sh from a BIG-IP running 11.6 HF5. Python is installed as mentioned

[root@bigip-ve:Active:Standalone] appsvcs_integration_iapp-develop # ./build.sh
Generating APL...
  File "util/build_apl.py", line 61
    with open(sys.argv[1]) as data_file:
            ^
SyntaxError: invalid syntax
Generating docs...
  File "util/build_doc.py", line 40
    with open(sys.argv[1]) as data_file:
            ^
SyntaxError: invalid syntax
Assembling template...
  File "util/build_tmpl.py", line 7
    with open("%s/src/implementation_layer.tcl" % basedir,"r") as impl:
            ^
SyntaxError: invalid syntax

 # python -V
Python 2.4.3

I used another system to do it  
nicolas@Kayndar:~/appsvcs_integration_iapp-develop$ python -V
Python 2.7.5+

Would be good to mention which python version is required

thanks! Keep up the good work :)

**Comment by 0xHiteshPatel** [comment]
The 'with' statement requires python 2.6, which BIG-IP does not have.  My assumption was that the build would run on a separate system, not BIG-IP.  

I'll add the version number to the README to make things clear.
