### ISSUE TITLE
BIG-IQ field names

### ISSUE THREAD

**Issue by nmenant** [0xHiteshPatel/appsvcs_integration_iapp#8]
I generated an iApp v0.3__006 and i saw the following into BIG-IP: 

i have two fields in the advanced properties Virtual Server: Name. One is definitely the pool name (default value is my_pool) and the other one is likely to be the VS name: (default value is my_virtualserver). 

in the text section of the app i generated i have a line which is:
pool.Name "Virtual Server: Name"     // i believe it should be pool.name "Pool: Name"

**Comment by 0xHiteshPatel** [comment]
Corrected the field description.  You'll have to run build.sh.
