### ISSUE TITLE
Use partition default route domain if no route domain given

### ISSUE THREAD

**Issue by vsnine** [0xHiteshPatel/appsvcs_integration_iapp#9]
Hi, I'd like to know if its possible to have the route domain filled in automagically if the target system has a partition default route domain AND no route domain was specified during deployment. In BIG-IP mode at least, if one is not specified now, it will fall back into RD 0 even if there is a partition default.

**Comment by 0xHiteshPatel** [comment]
Good idea.  I was already working on better support for partitions and route domains but hadn't considered this use case.  I'll add it to the list to get done.

**Comment by 0xHiteshPatel** [comment]
Done.  Checked into v0.3(020)_013

**Comment by vsnine** [comment]
Thanks. I tested the new updates and so far it works well.
